# Generated by Django 2.2.4 on 2019-08-12 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('lat_start', models.DecimalField(decimal_places=17, max_digits=20)),
                ('lng_start', models.DecimalField(decimal_places=17, max_digits=20)),
                ('lat_end', models.DecimalField(decimal_places=17, max_digits=20)),
                ('lng_end', models.DecimalField(decimal_places=17, max_digits=20)),
                ('audio_path', models.CharField(max_length=256)),
                ('audio_display', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
