# Generated by Django 2.2.4 on 2019-08-12 16:58

from django.db import migrations, models
import maps.apps


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='audio_path',
        ),
        migrations.AlterField(
            model_name='route',
            name='audio_display',
            field=models.FileField(null=True, upload_to=maps.apps.get_audio_upload_path),
        ),
    ]
