# Generated by Django 2.2.4 on 2019-08-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20190812_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='surfaces',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
