# Generated by Django 2.2.4 on 2019-08-14 23:17

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_route_surfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='surfaces',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
