# Generated by Django 2.2.4 on 2019-08-17 22:45

from django.db import migrations, models
import maps.apps


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20190815_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bike_shops',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='elevation_profile',
            field=models.ImageField(null=True, upload_to=maps.apps.get_elevation_upload_path),
        ),
    ]
